### ISSUE TITLE
Eclipse 3.5.1 does not find the project.

### ISSUE THREAD

**Issue by ollekullberg** [musk/SbtEclipsify#1]
Hi

Eclipse 3.5.1
Scala 2.7.7 
Scala Eclipse plugin (2.8.0 Beta1)

I do not know if I am doing this wrong or what? I tried the 0.5.0 build and basically did this to my project: 

<pre>
cd project/build
mkdir plugins
cd plugins
vi MySbtProjectPlugins.scala
</pre>

With this content: 

<pre>
 import sbt._

 class MySbtProjectPlugins(info: ProjectInfo) extends PluginDefinition(info) {
       lazy val eclipse = "de.element34" % "sbt-eclipsify" % "0.5.0"
 }
</pre>

I updated the project file:

<pre>
import sbt._
import de.element34.sbteclipsify._

class BookProject(info: ProjectInfo) extends DefaultProject(info) with SbtEclipsifyPlugin{
  lazy val testMe = task {
    println("Book Project Test Output"); None
  }
}
</pre>

I did "reload" and "eclipse" with the following output:

<pre>
 reload
[info] Recompiling plugin definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info]
[info] Updating plugins...
[info] downloading http://scala-tools.org/repo-releases/de/element34/sbt-eclipsify/0.5.0/sbt-eclipsify-0.5.0.jar ...
[info]  [SUCCESSFUL ] de.element34#sbt-eclipsify;0.5.0!sbt-eclipsify.jar (420ms)
[info] downloading http://scala-tools.org/repo-releases/org/scalatest/scalatest/1.0/scalatest-1.0.jar ...
[info]  [SUCCESSFUL ] org.scalatest#scalatest;1.0!scalatest.jar (2281ms)
[info] :: retrieving :: plugin-builder#plugin-builder_2.7.7 [sync]
[info]  confs: [compile, runtime, test, provided, system, optional, sources, javadoc]
[info]  3 artifacts copied, 0 already retrieved (5329kB/148ms)
[success] Plugins updated successfully.
[info]
[info]  Extracted source plugin ./lib_managed/scala_2.7.7/sbt-eclipsify-0.5.0.jar ...
[info] Recompiling plugin...
[info]    Source analysis: 3 new/modified, 0 indirectly invalidated, 0 removed.
[info] Recompiling project definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] Building project Programmera i Scala exempel 1.0 against Scala 2.7.7
[info]    using BookProject with sbt 0.7.1 and Scala 2.7.7
<prompt>&gt;</prompt> <userinput>eclipse</userinput>
[info]
[info] 
[info] Creating eclipse project...
[info] 
[success] Successful.
[info]
[info] Total time: 0 s, completed Feb 28, 2010 8:18:46 PM
</pre>

I got the .classpath and the .project files:

<pre>
<?xml version="1.0" encoding="utf-8" ?>
<projectDescription>
  <name>examples</name>
  <comment>Programmera i Scala exempel 1.0</comment>
  <projects></projects>
  <buildSpec>
    <buildCommand>
      <name>ch.epfl.lamp.sdt.core.scalabuilder</name>
    </buildCommand>
  </buildSpec>
  <natures>
    <nature>ch.epfl.lamp.sdt.core.scalanature</nature>
    <nature>org.eclipse.jdt.core.javanature</nature>
  </natures>
</projectDescription>
</pre>

and 

<pre>
<?xml version="1.0" encoding="UTF-8" ?>
<classpath>
<classpathentry kind="src" path="./src/test/scala" output="./target/scala_2.7.7/test-classes" including="**/*.scala" />
<classpathentry kind="src" path="./src/main/scala" including="**/*.scala" />
<classpathentry kind="con" path="ch.epfl.lamp.sdt.launching.SCALA_CONTAINER" />
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER" />
<classpathentry kind="output" path="./target/scala_2.7.7/classes" />
</classpath>
</pre>

But still, when I start Eclipse and load the workspace (HOME)/book (where my examples project reside) Eclipse does not find any project.

However, when I start Eclipse with some other workspace, I am able to import the project into the workspace. 

I dont know if this is the recommended way or if this is a bug?

**Comment by ollekullberg** [comment]
Ok, the XML files did not show, but if you press "edit" on this post you can see the content.

**Comment by musk** [comment]
You need to import the project into your eclipse workspace so that eclipse knows that you want to use it as project.
Go to File -> Import -> Existing Projects into Workspace 
In the dialog that pops up browse to the directory of your project and select it and press ok. You should see your project in the list of choosable project. When you press ok the project is imported and available in your workspace.

When you have done this once it is enough to just press F5 or choose Refresh for the project in order to update the created classpath and project file for this project.
