### ISSUE TITLE
SbtEclipsify don't put scala-compiler on the classpath

### ISSUE THREAD

**Issue by peewhy** [musk/SbtEclipsify#11]
Hi,

There is a problem when using SbtEclipsify with Lift projects.

From the Sbt documentation:

"sbt excludes all dependencies on scala-library.jar and scala-compiler.jar so that these will not be downloaded. sbt does this because it already provides the right versions of scala-library.jar and scala-compiler.jar required for normal use. In particular,
- If your main sources depend on scala-compiler.jar, scala-compiler.jar is added to runClasspath so that compiler classes are available for the run command.
- If your test sources depend on scala-compiler.jar, scala-compiler.jar is added to testClasspath so that the compiler classes are available for tests."

SbtEclipsify do not add scala-compiler to the Eclipse classpath, even if it is explicitely declared. (this may be related to the fact that such dependency declaration is not needed with sbt).

For an example of the problem, one can use any Lift project example. This example include a LiftConsole.scala file:

```
import _root_.bootstrap.liftweb.Boot
import _root_.scala.tools.nsc.MainGenericRunner

object LiftConsole {
  def main(args : Array[String]) {
    // Instantiate your project's Boot file
    val b = new Boot()
    // Boot your project
    b.boot
    // Now run the MainGenericRunner to get your repl
    MainGenericRunner.main(args)
    // After the repl exits, then exit the scala script
    exit(0)
  }
}
```

This will not compile in the Eclipse project because MainGenericRunner belongs to scala-compiler.

Adding scala-compiler dependency explicitely to the build file does not help since the dependency is not processed by sbtEclipsify.

**Comment by marvinthepa** [comment]
I am affected by this as well.
Workaround: manually putting the scala-compiler.jar in the .classpath file:
<classpath>
...
    <classpathentry kind="lib" path="project/boot/scala-2.8.1/lib/scala-compiler.jar" />
...
</classpath>

**Comment by olts-develop** [comment]
Am affected by this as well, also in conjunction with Lift. 

The following line needs to be added to the ".classpath" file:

classpathentry kind="con" path="org.scala-ide.sdt.launching.SCALA_COMPILER_CONTAINER"

Manual workaround: 

Each time you execute "eclipse" in SBT, you need to go to your project properties

Java Build Path/Libraries ...

Here click the button: "Add Library ..."
Choose the "Scala Compiler" line in the list, press "Next" and "Finish".

**Comment by thesamet** [comment]
Just wanted to confirm the problem as well. Happened with Scala 2.9.0.1 and Lift 2.4-M1 blank SBT project using SbtEclipsify 0.7 (cloned from github)

**Comment by musk** [comment]
I just saw this issue! Sorry gmail did not notify me. Currently I'm trying to port sbtEclipsify to sbt 0.10 and hopefully this will fix this issue. If not I will at least provide a mean to add the dependency for eclipse command.

**Comment by musk** [comment]
The 0.10.0 issue is out can you check if this still holds for the new version. A SNAPSHOT version is published to scala-tools.org. Simply add 0.10.0-SNAPSHOT to your library dependencies (see README for details)
