### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by andreasW** [musk/SbtEclipsify#13]
I love the idea of the eclipsify plugin, but I have not been able to get it to work. Of course, I blame my own stupidity first, but I also suspect the documentation could easily be clarified a bit ;-)

In the instructions, it says: 

Easiest is to add a dependency to the plugin in your plugin defintion "de.element34" % "sbt-eclipsify" % "<version>". Calling reload in sbt will pull in the needed dependency.

I tried to do so, but I get an error: "Unresolved dependencies: de.element34#sbt-eclipsify;0.4.0 not found"

It also says:

You can find ready made jars in the dist folder on git. Download it and use sbt local dependency feature in order to install it in your project.

I suspect that this is what I am missing, but I cannot follow the instructions, because I have not been able to figure out what the "local dependency feature" is, and how to use it. What would be nice if explicit steps were given on how to accomplish this.

Thanks for any help,

Andreas

[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      ::          UNRESOLVED DEPENDENCIES         ::
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      :: de.element34#sbt-eclipsify;0.4.0: not found
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[info] 
[info] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[error] sbt.ResolveException: unresolved dependency: de.element34#sbt-eclipsify;0.4.0: not found
sbt.ResolveException: unresolved dependency: de.element34#sbt-eclipsify;0.4.0: not found

 Hit enter to retry or 'exit' to quit:

**Comment by musk** [comment]
Yes the documentation needs updates. The problem you are having is
basically that you are using and outdated version. The current release
is 0.7.0 so you need to use "de.element34" % "sbt-eclipsify" %
"0.7.0".

Here is a simple example of a plugin definition which works for me:
import sbt._

class Plugins(info: ProjectInfo) extends PluginDefinition(info) {
    lazy val eclipse = "de.element34" % "sbt-eclipsify" % "0.7.0"
}

hope that helps

-Stefan

2011/5/26 andreasW
reply@reply.github.com:

**Comment by mrlimbic** [comment]
I had done this and has been working fine for a while using "de.element34" % "sbt-eclipsify" % "0.7.0"

Today, sbt update is failing and appears to be looking for 0.8.. Why? Here is the message

[error] sbt.ResolveException: unresolved dependency: de.element34#sbt-eclipsify_2.8.1;0.8.0-SNAPSHOT: not found
[info] == update ==
[error] Error running update: sbt.ResolveException: unresolved dependency: de.element34#sbt-eclipsify_2.8.1;0.8.0-SNAPSHOT: not found

Any advice?

**Comment by musk** [comment]
I do not have a 0.8.0 Version released. I reengineered the plugin to
work with sbt 0.10.x and above and there is only a SNAPSHOT release
for 2.9.1 as I have not had time to do more in the past five weeks.

So your only bet is to get the 0.8.0 branch from github and compile it
yourself. Sorry.

Regards
Stefan

2011/10/19 John Baker
reply@reply.github.com:

**Comment by mrlimbic** [comment]
It turned out I had a conflict in that it was defined twice once with 0.7 and once with 0.8. Removing the 0.8 reference fixed my problem. Thanks.
