### ISSUE TITLE
Server access error

### ISSUE THREAD

**Issue by andreasW** [musk/SbtEclipsify#15]
I finally broke down and decided to build eclipsify myself, but was quickly thwarted in this attempt also. After 

git clone https://github.com/musk/SbtEclipsify.git

and

cd SbtEclipsify; sbt update

I got, after a while, this error:

Getting net.java.dev.jna jna 3.2.3 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    1 artifacts copied, 0 already retrieved (838kB/46ms)
Getting Scala 2.7.7 ...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    2 artifacts copied, 0 already retrieved (9911kB/161ms)
Getting org.scala-tools.sbt sbt_2.7.7 0.7.4 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    15 artifacts copied, 0 already retrieved (4096kB/136ms)
[info] Recompiling plugin definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] 
[info] Updating plugins...
[error] Server access Error: Connection timed out url=http://tristanhunt.com:8081/content/groups/public/net/databinder/posterous-sbt/0.1.4/posterous-sbt-0.1.4.pom

This, for now, concludes my adventures in eclipsify and I will be waiting for inspiration in the form of a helpful tip before I pick it up again. I hope someone is listening on this channel....

Cheers,

Andreas

**Comment by musk** [comment]
The problem  seems to be that the posterouse plugin website is not available. This is a general problem which I have not found the time to correct yet. for the time being simply drop the posterous dependency in the plugin definition as that is not nessecary for the build. 
Sorry for the inconvenience. I will try to update the documentation to make this point more clear.
