### ISSUE TITLE
SbtEclipsify exception when building Eclipse project for Dispatch

### ISSUE THREAD

**Issue by NYCBrit** [musk/SbtEclipsify#18]
I've modified the Databinder Dispatch plugin & project to add Eclipsify, but it gives me the following error when I run the "eclipse" command :
Error running eclipse: java.lang.ClassCastException: DispatchProject cannot be cast to sbt.BasicScalaPaths

I'm using sbt-eclipsify 0.7.0, building Dispatch with Scala 2.8.0

**Comment by musk** [comment]
You should use the 0.8 branch. You will have to build it yourself. Just
delete the plugins directory to get rid of unnecessary dependencies.
Am 05.06.2011 20:43 schrieb "NYCBrit" <
reply@reply.github.com>:

**Comment by musk** [comment]
The 0.10 branch has just been released as a SNAPSHOT version please use this and check if the error prevails
