### ISSUE TITLE
java.lang.ClassCastException: xxxxxxxxxxxProject cannot be cast to sbt.BasicScalaPaths

### ISSUE THREAD

**Issue by E-Fir** [musk/SbtEclipsify#19]
> eclipse
> [info]
> [info] == eclipse ==
> [info] Creating eclipse project...
> java.lang.ClassCastException: xxxxxxxxxxxProject cannot be cast to sbt.BasicScalaPaths
>         at de.element34.sbteclipsify.ClasspathFile.writeFile(ClasspathFile.scala:67)
>         at de.element34.sbteclipsify.Eclipsify$class.writeClasspathFile(SbtEclipsify.scala:71)
>         at RenoiseAssistantProject.writeClasspathFile(RenoiseAssistantProject.scala:4)
>         at de.element34.sbteclipsify.Eclipsify$$anonfun$eclipse$1.apply(SbtEclipsify.scala:43)
>         at de.element34.sbteclipsify.Eclipsify$$anonfun$eclipse$1.apply(SbtEclipsify.scala:40)
>         at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
>         at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
>         at sbt.impl.RunTask.runTask(RunTask.scala:85)
>         at sbt.impl.RunTask.run(RunTask.scala:32)
>         at sbt.impl.RunTask$.apply(RunTask.scala:17)
>         at sbt.impl.RunTask$.apply(RunTask.scala:16)
>         at sbt.Project$class.run(Project.scala:98)
>         at sbt.Project$class.act(Project.scala:129)
>         at sbt.ParentProject.act(BasicProjectTypes.scala:559)
>         at sbt.xMain$$anonfun$8.apply(Main.scala:530)
>         at sbt.xMain$$anonfun$8.apply(Main.scala:530)
>         at sbt.xMain.withAction(Main.scala:563)
>         at sbt.xMain.sbt$xMain$$handleAction(Main.scala:530)
>         at sbt.xMain.handleCommand(Main.scala:520)
>         at sbt.xMain.processAction(Main.scala:459)
>         at sbt.xMain.process$1(Main.scala:257)
>         at sbt.xMain$Continue$1.apply(Main.scala:132)
>         at sbt.xMain.run$1(Main.scala:136)
>         at sbt.xMain.processArguments(Main.scala:266)
>         at sbt.xMain.startProject(Main.scala:107)
>         at sbt.xMain.run(Main.scala:84)
>         at sbt.xMain.run0$1(Main.scala:35)
>         at sbt.xMain.run(Main.scala:42)
>         at xsbt.boot.Launch$.run(Launch.scala:53)
>         at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
>         at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
>         at xsbt.boot.Launch$.launch(Launch.scala:57)
>         at xsbt.boot.Launch$.explicit(Launch.scala:42)
>         at xsbt.boot.Launch$.initialized(Launch.scala:38)
>         at xsbt.boot.Launch$.parsed(Launch.scala:31)
>         at xsbt.boot.Launch$.configured(Launch.scala:21)
>         at xsbt.boot.Launch$.apply(Launch.scala:16)
>         at xsbt.boot.Launch$.apply(Launch.scala:13)
>         at xsbt.boot.Boot$.runImpl(Boot.scala:24)
>         at xsbt.boot.Boot$.run(Boot.scala:19)
>         at xsbt.boot.Boot$.main(Boot.scala:15)
>         at xsbt.boot.Boot.main(Boot.scala)
> [info] == eclipse ==
> [error] Error running eclipse: java.lang.ClassCastException: xxxxxxxxxxxProject cannot be cast to sbt.BasicScalaPaths

**Comment by musk** [comment]
Please recheck with 0.10 version and reopen if error prevails
