### ISSUE TITLE
How hard is it to make this work for Scala 2.8?

### ISSUE THREAD

**Issue by ollekullberg** [musk/SbtEclipsify#2]
I tried this plugin for a Scala 2.8.0 Beta1 project, but nothing happened during reload and "eclipse" command was not recognized. I need 2.8.0 support. Is this hard to add?

**Comment by musk** [comment]
Are you using the newest sbt version? What is the setup of your project. Currently the plugin needs a 2.7.7 sbt runtime but works with a 2.8.0 scala version for building for me. 
Can you provide your plugin definition and your build.properties file?

**Comment by ollekullberg** [comment]
Thanks for the quick reply. 

 I am using SBT 0.7.1.

It is the same setup as in the other issue description, except that SBT is using Scala 2.8.0 Beta1 for build but 2.7.7 otherwise. (I am not sure why it is like that).

I created an SBT project just by typing sbt, and then added a HelloWorld.scala under /src/main/scala.  Typed >run  and I could see the "Hello World!". But when I added the /project/build/plugin/MySbtProject.scala and added the "with" clause in the /project/build/HelloProject.scala and typed "reload" nothing happened and the "eclipse" command was not recoginized.

**Comment by ollekullberg** [comment]
my SCALA_HOME points to 2.8.0 Beta1 but both 2.8.0/bin and 2.7.7/bin is in my PATH (2.7.7 in the end). I could not find the code that added Scala 2.7.7/bin to the end of my PATH, I want to completely move up to 2.8.0  :-)

**Comment by musk** [comment]
It is normal that 0.7.x uses Scala 2.7.7 to run. Important is that your build version is set to 2.8.0 in oder to use it. 
The plugin definition file needs to reside in a directory named plugins not plugin. In this file you need to add the dependency for this plugin but the trait SbtEclipsifyPlugin has to be added to the project file in project/build/Project.scala. 
Take a look at this plugins plugin and project scala file to see how to use it as it uses the Eclipse plugin itself.

**Comment by ollekullberg** [comment]
My bad, I found that the "plugins" directory was correctly spelled, but it was placed inside the build directory. When I changed it to /project/plugins/MySbtProject.scala it worked out fine..  its all in the details it seems :-)  Thanky thanky!
