### ISSUE TITLE
Scala 2.9 and sbt 0.10 support

### ISSUE THREAD

**Issue by john76** [musk/SbtEclipsify#20]
Do you have any plans to support these?

**Comment by musk** [comment]
Yes. But I can't really tell when as I have just come back from a two
week holiday and I still have a backlog to work on.

I will try to get to it asap.

-Stefan

2011/6/25 john76
reply@reply.github.com:

**Comment by NYCBrit** [comment]
How's it looking?

**Comment by musk** [comment]
The first commits are in for 0.10.1 sbt but I'm still exploring some
options. I think I will get a working snapshot version out by the end
of next week maybe earlier depending on time.
Basically everything is setup except for source attachment and project
dependencies.

Go grab the sources from the 0.10 branch and see how far you get. It
is buildable but not workable just yet.

Regards
Stefan

2011/7/18 NYCBrit
reply@reply.github.com:

**Comment by musk** [comment]
I finally managed to push the 0.10 branch out and merged it with master. A SNAPSHOT version is published to scala-tools.org. Simply add the SNAPSHOT repository as a resolver and add 0.10.0-SNAPSHOT as a library dependencies in your global plugins file or add it to your local build file.

**Comment by NYCBrit** [comment]
ok, I've added the sbtEclipsify dependency & snapshot resolver to the project, but I have no "eclipse" action. Do I need to set up a global plugins file in ~.sbt\plugins? If so, what do I put in it?
Thanks!

**Comment by NYCBrit** [comment]
Solved it. Created a global plugin file (C:\users<me>.sbt\plugins\build.sbt) containing :

resolvers += ScalaToolsSnapshots

libraryDependencies += "de.element34" %% "sbt-eclipsify" % "0.10.0-SNAPSHOT"

**Comment by musk** [comment]
Yes as long as I do not make a release you have to add teh ScalaToolsSnapshot as a resolver. As soon as I do not hear anymore complains I will make an official release for 0.10.0
