### ISSUE TITLE
Does not work with android-plugin

### ISSUE THREAD

**Issue by michel-slm** [musk/SbtEclipsify#3]
I'm trying to use SbtEclipsify 0.5.0 with sbt 0.7.1, scala 2.7.7 and android-plugin 0.4.1. On a test project without android-plugin, "sbt eclipse" works fine. The android project without SbtEclipsify also works fine. When using both together, however, the project compiles, but sbt eclipse fails:

[info] == eclipse ==
[error] Error running eclipse: java.lang.ClassCastException: HelloAndroid cannot be cast to sbt.BasicScalaPaths
[info] 
[info] Total time: 0 s, completed Mar 22, 2010 5:42:27 PM
[info] 
[info] Total session time: 1 s, completed Mar 22, 2010 5:42:27 PM
[error] Error during build.

**Comment by michel-slm** [comment]
Ah, false alarm. the Android skeleton project generated has a more complex build process with subtasks; if I extend the main subtask with SbtEclipsifyPlugin then things work fine

**Comment by musk** [comment]
Glad you could resolve your issue. Would it be possible to get the sources for this project? Or is this just the basic skeleton one gets when executing the android plugin? I'd like to see if I can make the use of SbtEclipsePlugin more convinient in this case or at least document it in the readme properly.

-musk
