### ISSUE TITLE
.classpath file for subprojects not relative to subproject

### ISSUE THREAD

**Issue by dholbrook** [musk/SbtEclipsify#4]
the generated .classpath file for subprojects has some elements that are produced as relative to the parent project rather than the subproject.  Here is an example with the actual supbroject name replaced with "[subproject]"

   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
  &lt;classpath&gt;
  &lt;classpathentry kind=&quot;src&quot; path=&quot;.[subproject]\src\test\scala&quot; output=&quot;.[subproject]\target\scala_2.8.0.RC2\test-classes&quot; including=&quot;**/*.scala&quot; /&gt;
  &lt;classpathentry kind=&quot;src&quot; path=&quot;.[subproject]\src\main\scala&quot; including=&quot;**/*.scala&quot; /&gt;
  &lt;classpathentry kind=&quot;lib&quot; path=&quot;lib_managed\scala_2.8.0.RC2\test\junit-4.8.1.jar&quot; /&gt;
  &lt;classpathentry kind=&quot;lib&quot; path=&quot;lib_managed\scala_2.8.0.RC2\test\mockito-all-1.8.4.jar&quot; /&gt;
  &lt;classpathentry kind=&quot;lib&quot; path=&quot;lib_managed\scala_2.8.0.RC2\compile\commons-pool-1.5.4.jar&quot; /&gt;
  &lt;classpathentry kind=&quot;lib&quot; path=&quot;lib_managed\scala_2.8.0.RC2\compile\commons-dbcp-1.4.jar&quot; /&gt;
  &lt;classpathentry kind=&quot;lib&quot; path=&quot;lib_managed\scala_2.8.0.RC2\compile\hsqldb-1.8.0.10.jar&quot; /&gt;
  &lt;classpathentry kind=&quot;lib&quot; path=&quot;lib_managed\scala_2.8.0.RC2\test\scalatest-1.2-for-scala-2.8.0.RC2-SNAPSHOT.jar&quot; /&gt;
  &lt;classpathentry kind=&quot;con&quot; path=&quot;ch.epfl.lamp.sdt.launching.SCALA_CONTAINER&quot; /&gt;
  &lt;classpathentry kind=&quot;con&quot; path=&quot;org.eclipse.jdt.launching.JRE_CONTAINER&quot; /&gt;
  &lt;classpathentry kind=&quot;output&quot; path=&quot;.[subproject]\target\scala_2.8.0.RC2\classes&quot; /&gt;
  &lt;/classpath&gt;

**Comment by musk** [comment]
Pulled your fix!
I'm currently checking it and will integrate it into master as soon as possible.

Thanks.

**Comment by musk** [comment]
Integrated and fixed in 0.5.4
