### ISSUE TITLE
ClasspathFileTest.scala:33: value scalatest is not a member of package org

### ISSUE THREAD

**Issue by MaxDesiatov** [musk/SbtEclipsify#5]
doing this:

<pre>
$ git clone git://github.com/musk/SbtEclipsify.git
$ cd SbtEclipsify
$ sbt
Getting Scala 2.7.7 ...
:: retrieving :: org.scala-tools.sbt#boot-scala
        confs: [default]
        2 artifacts copied, 0 already retrieved (9911kB/216ms)
Getting org.scala-tools.sbt sbt_2.7.7 0.7.4 ...
:: retrieving :: org.scala-tools.sbt#boot-app
        confs: [default]
        15 artifacts copied, 0 already retrieved (4096kB/134ms)
[info] Recompiling plugin definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] 
[info] Updating plugins...
[info] downloading http://scala-tools.org/repo-releases/net/databinder/posterous-sbt/0.1.4/posterous-sbt-0.1.4.jar ...
[info]  [SUCCESSFUL ] net.databinder#posterous-sbt;0.1.4!posterous-sbt.jar (159ms)
[info] downloading http://scala-tools.org/repo-releases/de/element34/sbt-eclipsify/0.5.4/sbt-eclipsify-0.5.4.jar ...
[info]  [SUCCESSFUL ] de.element34#sbt-eclipsify;0.5.4!sbt-eclipsify.jar (315ms)
[info] downloading http://tristanhunt.com:8081/content/groups/public/com/tristanhunt/knockoff_2.7.7/0.6.1-9/knockoff_2.7.7-0.6.1-9.jar ...
[info]  [SUCCESSFUL ] com.tristanhunt#knockoff_2.7.7;0.6.1-9!knockoff_2.7.7.jar (2014ms)
[info] downloading http://scala-tools.org/repo-releases/net/databinder/dispatch-http_2.7.7/0.7.0/dispatch-http_2.7.7-0.7.0.jar ...
[info]  [SUCCESSFUL ] net.databinder#dispatch-http_2.7.7;0.7.0!dispatch-http_2.7.7.jar (955ms)
[info] downloading http://repo1.maven.org/maven2/org/scala-tools/testing/scalatest/0.9.5/scalatest-0.9.5.jar ...
[info]  [SUCCESSFUL ] org.scala-tools.testing#scalatest;0.9.5!scalatest.jar (4853ms)
[info] downloading http://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar ...
[info]  [SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.0.1!httpclient.jar (1093ms)
[info] downloading http://scala-tools.org/repo-releases/net/databinder/dispatch-futures_2.7.7/0.7.0/dispatch-futures_2.7.7-0.7.0.jar ...
[info]  [SUCCESSFUL ] net.databinder#dispatch-futures_2.7.7;0.7.0!dispatch-futures_2.7.7.jar (1221ms)
[info] downloading http://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar ...
[info]  [SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.0.1!httpcore.jar (1408ms)
[info] downloading http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar ...
[info]  [SUCCESSFUL ] commons-logging#commons-logging;1.1.1!commons-logging.jar (322ms)
[info] downloading http://repo1.maven.org/maven2/commons-codec/commons-codec/1.3/commons-codec-1.3.jar ...
[info]  [SUCCESSFUL ] commons-codec#commons-codec;1.3!commons-codec.jar (310ms)
[info] :: retrieving :: plugin-definition#plugin-definition_2.7.7 [sync]
[info]  confs: [compile, runtime, test, provided, system, optional, sources, javadoc]
[info]  10 artifacts copied, 0 already retrieved (2001kB/56ms)
[success] Plugins updated successfully.
[info] 
[info]  Extracted source plugin ./lib_managed/scala_2.7.7/posterous-sbt-0.1.4.jar ...
[info]  Extracted source plugin ./lib_managed/scala_2.7.7/sbt-eclipsify-0.5.4.jar ...
[info] Recompiling plugin...
[info]    Source analysis: 7 new/modified, 0 indirectly invalidated, 0 removed.
[info] Recompiling project definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[warn] Credentials file /Users/maxd/.credentials does not exist
[info] Building project sbt-eclipsify 0.6.0 against Scala 2.7.7
[info]    using SbtEclipsifyPluginProject with sbt 0.7.4 and Scala 2.7.7
> publish-local
[info] 
[info] == compile ==
[info]   Source analysis: 6 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[info] Compilation successful.
[info]   Post-analysis: 65 classes.
[info] == compile ==
[info] 
[info] == copy-resources ==
[info] == copy-resources ==
[info] 
[info] == test-compile ==
[info]   Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling test sources...
[error] /Users/maxd/Documents/SbtEclipsify/src/test/scala/de/element34/sbteclipsify/ClasspathFileTest.scala:33: value scalatest is not a member of package org
[error] import org.scalatest._
[error]            ^
[error] /Users/maxd/Documents/SbtEclipsify/src/test/scala/de/element34/sbteclipsify/ClasspathFileTest.scala:40: value should is not a member of java.lang.String
[error]   "A ClasspathEntry" should "produce the xml for a classpathentry in the elcipse .classpath file" in {
[error]                      ^
[error] two errors found
[info] == test-compile ==
[info] 
[info] == copy-test-resources ==
[info] == copy-test-resources ==
[error] Error running test-compile: Compilation failed
[info] 
[info] Total time: 5 s, completed Oct 19, 2010 4:35:32 PM
>
</pre>

**Comment by musk** [comment]
Seems like I'm still referencing the snapshot version of scalatest. If you cannot wait try to swap the scalatest version in the Project.scala file for one that is current. I will get on it as soon as I have some time.

**Comment by MaxDesiatov** [comment]
pulling the latest changes didn't help.  also tried to clone from scratch, removing old sbt cache, same error: value scalatest is not a member of package org

**Comment by musk** [comment]
This is weird. When I do a fresh checkout publish-local throws the error you are mentioning. When I run test and after that publish-local everything works fine. 
Maybe this is an error in the way publish-local does things. I'll check on the sbt mailing list to see if someone can point me to the problem. In the mean time try to do a sbt test publish-local

**Comment by MaxDesiatov** [comment]
no, sbt test publish-local doesn't help.  however, sbt update publish-local works for me

**Comment by musk** [comment]
Sbt requires you to do a update on a fresh update to get all dependencies loaded. This is expected behaviour for sbt. I will update the documentation to make this explicit.
